### ISSUE TITLE
graphics examples link 404s

### ISSUE THREAD

**Issue by tomhannen** [ft-interactive/visual-vocabulary#156]
The link in the instructions to http://ft-interactive.github.io/graphics-examples/ goes to a 404.

**Comment by kavanagh** [comment]
Fixed read me: https://github.com/ft-interactive/visual-vocabulary/commit/2ddf2c773c6e49f18429c6de07e9eb9e35d55fd0

**Comment by kavanagh** [comment]
Also added this to redirect other broken links: https://github.com/ft-interactive/ft-interactive.github.io/blob/production/app/graphics-examples/index.html#L1
