### ISSUE TITLE
Mono print versions

### ISSUE THREAD

**Issue by digitalcampbell** [ft-interactive/visual-vocabulary#30]
Templates to create a colour and mono version of the print charts

Colour and corresponding mono value attached

![screen shot 2015-12-04 at 11 49 34](https://cloud.githubusercontent.com/assets/11406465/11589040/1fc83ec6-9a7d-11e5-8f51-4fc8f1cae881.png)

**Comment by alansmithy** [comment]
We're not going to pursue mono versionsfor print given auto-mono generation
